networks:
  tzar:

services:
  app:
    container_name: feru_cars_app
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7001:7000
    networks:
      tzar:

  db:
    container_name: feru_cars_db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: feru
      POSTGRES_DB: ferudb
    ports:
      - 5432:5432
    networks:
      tzar: